<?php

namespace ContainerEJiGcO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJeuxControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\JeuxController' shared autowired service.
     *
     * @return \App\Controller\JeuxController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\JeuxController'] = $instance = new \App\Controller\JeuxController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\JeuxController', $container));

        return $instance;
    }
}
